GET http://localhost:4000/api/producto


###
POST http://localhost:4000/api/producto
Content-Type: application/json

{
    "nombre": "radio",
    "precio": 50.00,
    "imagen": "imagen.jpg",
    "cantidad": 7,
    "descripcion": "Bueno bonito y barato"
}


###
GET  http://localhost:4000/api/producto/4


###
PUT  http://localhost:4000/api/producto/2
Content-Type: application/json

{
    "nombre": "monitor modificado",
    "precio": 2500.00,
    "imagen": "imagen2.jpg",
    "cantidad": 7,
    "descripcion": "Bueno bonito y barato"
}


###
DELETE http://localhost:4000/api/producto/5